services:
  db:
    image: postgres:15
    container_name: ${POSTGRES_DB}-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5434:${POSTGRES_PORT}" # наружу отдаём на 5433, внутри всё ещё 5432

  bot:
    build: ./bot
    container_name: ${POSTGRES_DB}-bot
    restart: always
    depends_on:
      - db
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    env_file:
      - .env
