services:
  db:
    image: postgres:15-alpine
    container_name: tgl_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # Раскомментируйте при необходимости внешнего доступа к БД
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: tgl_bot
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: tgl_api
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_PORT}:8000"
    restart: unless-stopped

volumes:
  pgdata:
